spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wherego
    username: root
    password: 7575

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true